DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS Comments;

CREATE TABLE Users (
    Id INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL UNIQUE,
    Email TEXT NOT NULL UNIQUE,
    Password TEXT NOT NULL
);

CREATE TABLE Posts (
    Id INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
    Author INTEGER NOT NULL,
    Theme TEXT NOT NULL,
    Content TEXT NOT NULL,
    Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Likes INTEGER NOT NULL DEFAULT 0,
    Dislikes INTEGER NOT NULL DEFAULT 0,
    Tag TEXT NOT NULL,
    FOREIGN KEY (Author) REFERENCES Users (Id)
);

CREATE TABLE Comments (
    Id INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
    Post INTEGER NOT NULL,
    Author INTEGER NOT NULL,
    Content TEXT NOT NULL,
    Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Post) REFERENCES Posts (Id),
    FOREIGN KEY (Author) REFERENCES Users (Id)
);